---

- name: Reinstall guacd
  command: make install
  args:
    chdir: /usr/local/src/{{ source_directory }}
  notify: Restart guacd

- name: Restart guacd
  service:
    name: guacd
    state: restarted
    enabled: yes
